# Compiler and flags
CXX := g++
CXXFLAGS := -std=c++23 -Wall -Wextra -O3 -Iinclude

# Source and output directories
SRC_DIR := src
INC_DIR := include
SRC := $(wildcard $(SRC_DIR)/*.cpp)
BIN := main

# Default target
all: $(BIN)

# Compile target
$(BIN): $(SRC)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Clean target
clean:
	rm -f $(BIN)

# Phony targets
.PHONY: all clean